---
- name: update redhat packages
  yum:
    name: 
      - java-1.8.0-openjdk.x86_64
      - wget
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: update debian packages
  apt:
    name: 
      - openjdk-8-jdk
      - wget
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: create new directory
  file:
    path: /app
    state: directory

- name: Download nexus tar
  get_url:
    url: 	"https://download.sonatype.com/nexus/3/nexus-{{ nexus_version }}-unix.tar.gz" 
    dest: /app/nexus.tar.gz

- name: Unpack nexus.tar.gz
  unarchive:
    src: /app/nexus.tar.gz
    dest: /app
    remote_src: yes

- name: Rename to nexus folder
  copy:
    src: "/app/nexus-{{ nexus_version }}/"
    dest: /app/nexus/
    remote_src: yes
    directory_mode:
  tags:
    - dir_not_exist
    - dircontent

- name: Add nexus user
  user:
    name: nexus

- name: Change owner to nexus
  file:
    dest: "{{ item }}"
    owner: nexus
    group: nexus
    recurse: yes
  with_items:
    - /app/nexus
    - /app/sonatype-work

- name: Run as nexus user
  lineinfile:
    path: "/app/nexus/bin/nexus.rc"
    regexp: "^#"
    line: 'run_as_user="nexus"'
    state: present

- name: copy nexus.service to remote host
  copy:
    src: nexus.service
    dest: /etc/systemd/system/nexus.service
  notify: Restart nexus
