- name: config nexus machine 
  hosts: nexus
  become: true
  roles:
    - roles/nexus

- name: config sonarqube machine 
  hosts: sonarqube
  become: true
  roles:
    - roles/postgresql
    - roles/sonarqube